#! /bin/sh

xsetroot -cursor_name left_ptr
compton &
polybar top &
sxhkd &
ibus-daemon -drx &
~/.fehbg &

bspc config border_width         0
bspc config normal_border_color  "#252930"
bspc config focused_border_color "#f22b00"
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc config pointer_mod mod1
bspc config pointer_action1 move

bspc monitor -d tty internet code coms media other

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc rule -a urxvt state=floating
bspc rule -a firefox -o desktop='internet'

