config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_alacritty:
    dst: ~/.config/alacritty
    src: config/alacritty
  d_package.use:
    dst: /etc/portage/package.use
    src: etc/portage/package.use
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  f_bspwmrc:
    dst: ~/.config/bspwm/bspwmrc
    src: config/bspwm/bspwmrc
  f_compton:
    dst: /etc/portage/package.use/compton
    src: etc/portage/package.use/compton
  f_compton.conf:
    dst: ~/.config/compton/compton.conf
    src: config/compton/compton.conf
  f_feh:
    dst: /etc/portage/package.use/feh
    src: etc/portage/package.use/feh
  f_ffpmeg:
    dst: /etc/portage/package.use/ffpmeg
    src: etc/portage/package.use/ffpmeg
  f_make.conf:
    dst: /etc/portage/make.conf
    src: etc/portage/make.conf
  f_mesa:
    dst: /etc/portage/package.use/mesa
    src: etc/portage/package.use/mesa
  f_ncurses:
    dst: /etc/portage/package.use/ncurses
    src: etc/portage/package.use/ncurses
  f_nvidia:
    dst: /etc/portage/package.use/nvidia
    src: etc/portage/package.use/nvidia
  f_steam:
    dst: /etc/portage/package.use/steam
    src: etc/portage/package.use/steam
  f_sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: config/sxhkd/sxhkdrc
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_zz-autounmask:
    dst: /etc/portage/package.use/zz-autounmask
    src: etc/portage/package.use/zz-autounmask
profiles:
  desktop:
    dotfiles:
    - f_zshrc
    - d_polybar
    - f_compton.conf
    - f_sxhkdrc
    - f_bspwmrc
    - d_alacritty
    - f_xinitrc
  nekobox:
    dotfiles:
    - f_vimrc
    - f_make.conf
    - d_package.use
    - f_compton
    - f_feh
    - f_ffpmeg
    - f_mesa
    - f_ncurses
    - f_nvidia
    - f_steam
    - f_zz-autounmask
