#! /bin/sh

xsetroot -cursor_name left_ptr
compton --conf ~/.config/compton/compton.conf &
polybar left &
polybar right &
sxhkd &
ibus-daemon -drx &
~/.fehbg &

bspc config border_width         3
bspc config normal_border_color  "#dbdcdc"
bspc config focused_border_color "#c86ad4"
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc config pointer_mod mod1
bspc config pointer_action1 move

bspc monitor DP-4 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc rule -a Firefox desktop=^4
bspc rule -a TelegramDesktop desktop=^5
bspc rule -a discord desktop=^5
